export const FETCH_ACTORS_REQUEST = 'FETCH_ACTORS_REQUEST';
export const FETCH_ACTORS_SUCCESS = 'FETCH_ACTORS_SUCCESS';
export const FETCH_ACTORS_FAILURE = 'FETCH_ACTORS_FAILURE';

export const ADD_ACTOR_REQUEST = 'ADD_ACTOR_REQUEST';
export const ADD_ACTOR_SUCCESS = 'ADD_ACTOR_SUCCESS';
export const ADD_ACTOR_FAILURE = 'ADD_ACTOR_FAILURE';

export const FETCH_PRODUCERS_REQUEST = 'FETCH_PRODUCERS_REQUEST';
export const FETCH_PRODUCERS_SUCCESS = 'FETCH_PRODUCERS_SUCCESS';
export const FETCH_PRODUCERS_FAILURE = 'FETCH_PRODUCERS_FAILURE';

export const ADD_PRODUCER_REQUEST = 'ADD_PRODUCER_REQUEST';
export const ADD_PRODUCER_SUCCESS = 'ADD_PRODUCER_SUCCESS';
export const ADD_PRODUCER_FAILURE = 'ADD_PRODUCER_FAILURE';

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAILURE = 'ADD_MOVIE_FAILURE';

export const EDIT_MOVIE = 'EDIT_MOVIE';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE';
